### ISSUE TITLE
[BUG] Application doesn't display my account

### ISSUE THREAD

**Issue by danielwerg** [Primus27/R6-Profile-Switcher#5]
**Describe the bug**

Steam version
Application is looking for folder `1843` but I only got folder `1844`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to R6-Profile-Switcher
2. Click on "Find account"
3. "Select Account" box doesn't display my account

**Expected behavior**

Application should also look for folders named `1844`

**Screenshots**
![x](https://user-images.githubusercontent.com/35052399/108090431-83844b00-7072-11eb-8a8e-5aa206a3d199.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: BETA 4.1.0

**Comment by Primus27** [comment]
Thanks for posting. Everywhere I've checked seems to indicate that the folder is named "1843" for steam. Does the uplay launcher open for you when you start the game through steam? I'm just trying to understand why some users seem to get non 635 / 1843 folders.

I'll post an update for this tomorrow - I've finished working on the code; I just need to test it some more.

Thanks.

**Comment by danielwerg** [comment]
My other account is 1843, weird.
My guess is 1844 is id for RU version of game

**Comment by danielwerg** [comment]
See: https://github.com/wTonyChen/Uplay-AppID-List/blob/master/UplayAppIDs.json

Both of my accounts is steam version btw.

**Comment by Primus27** [comment]
Fixed in [Version 4.1.1](https://github.com/Primus27/R6-Profile-Switcher/commit/32864e054eef35b19cdef6e0e3be7e487edcdc10). I've pushed a new release :)
