### ISSUE TITLE
[BUG] App crashes on "Find account" click - New season (Y6S1)

### ISSUE THREAD

**Issue by Favo02** [Primus27/R6-Profile-Switcher#6]
**Describe the bug**
When pressing the button "Find account" in the main menu of the app it crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the app
2. Press "Find account"
3. The app disappear

**Expected behaviour**
To find the accounts in my pc.

**Screenshots**
https://streamable.com/fb2lji

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 20H2
 - Version Beta 4.2.0

**Comment by Primus27** [comment]
Found the issue. The logic to handle the first API is dodgy. This wasn't a problem before since the API rejected requests without an API key. I'll push a fix in a few hours.

**Comment by Primus27** [comment]
Fixed in [Version 4.3.0](https://github.com/Primus27/R6-Profile-Switcher/commit/f18eb678cce4568a7ecaef77f2d7f664e54a3498). I'll push a new release in about 10 mins.
